### PR TITLE
Docs

### PR DESCRIPTION
**Pull request by snazy**
includes images

### CODE REVIEW

**Comment by BenWhitehead** [comment]
Diagrams look good. My colleague is still reviewing the text version will get info added here when he's done.

**Comment by snazy** [comment]
Have worked in the review comments and rebased the branch. Will go over all docs today on my own so we can do another review round on this today.

**Comment by snazy** [comment]
OK, ready for another review round

**Comment by BenWhitehead** [comment]
ready to merge after a rebase

**Comment by snazy** [comment]
rebased

**Pull request merged**
