### PR TITLE
Role Support

### PR DESCRIPTION
**Pull request by VenkateshSub**
Added Mesos role support to the cassandra framework.

### CODE REVIEW

**Comment by VenkateshSub** [comment]
Worked on this collaboratively with @ritazh

Thanks!

**Comment by BenWhitehead** [comment]
Thanks for this @VenkateshSub and @ritazh I'll get this merged soon.

**Comment by BenWhitehead** [comment]
@VenkateshSub can you rebase is against `rewrite`? If not let me know and I can do it in another branch and then merge it but it won't be as clean for me.

**Comment by VenkateshSub** [comment]
Sure! Let me spend sometime on this later today and get back.

Thanks
Venkatesh
Cell# 612 568 3659

**Comment by BenWhitehead** [comment]
Awesome thanks!

**Comment by VenkateshSub** [comment]
Ben, Sorry just found sometime today to wrap this. 

Merged the code with the latest branch. But now I wonder, I probably should have done rebase right? Let me know what you feel, I can probably remove the latest commit and try to rebase it. 

Thanks!

**Comment by BenWhitehead** [comment]
@VenkateshSub yes, please rebase rather than just merging up.
Since you already created a commit with a merge up you might need to reset before you rebase.

possibly something like this:
```bash
git fetch --all
git checkout rewrite
git reset --hard HEAD~1
git rebase -i upstream/rewrite
git push --force origin rewrite
```

Careful with the `reset --hard` it will nuke anything in the process of resetting rather than un-committing.

**Comment by VenkateshSub** [comment]
Yep, I have rebased the code now! Feel free to let me know if you would like me to add a test :)

**Comment by BenWhitehead** [comment]
Thanks @VenkateshSub

**Pull request merged**
